## TSP problem

In [41]:
from QAOA.optimizers.CEM import CEM
from QAOA.problems.TSP import QAOA_TSP
from QAOA.problem_solver import ProblemSolver

In [44]:
import pennylane as qml


tsp = QAOA_TSP(
    number_of_cities=3,
    number_of_layers=6,
    optimization_steps=70,
    # optimizer=qml.GradientDescentOptimizer(stepsize=0.01)
    optimizer=qml.AdamOptimizer(
        stepsize=0.01,
        beta1=0.9,
        beta2=0.99
    )
)
# cem = CEM(
#     problem=tsp,
#     epochs=10,
#     samples_per_epoch=100,
#     elite_frac=0.1,
#     process=6
# )

# cem.minimize(init_weights=[1, 1, 1])

In [45]:
solver = ProblemSolver(tsp, qml.AdamOptimizer(stepsize=0.50))

In [ ]:
solver.run_learning([4, 1, 1], 1)

## Knapsack problem

In [59]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
from QAOA.QAOA_problems.Knapsack import Knapsack, QAOA_Knapsack
from QAOA.optimizers.CEM import CEM
from QAOA.optimizers.qml_gradient_descent import QmlGradientDescent
# from QAOA.problem_solver import ProblemSolver

import pennylane as qml
import numpy as np

In [66]:
knapsack = Knapsack(max_weight=2)
knapsack.set_knapsack([(2, 2), (3, 1)])

In [67]:
knapsack_qaoa = QAOA_Knapsack(
    knapsack, 
    # layers=3
    # number_of_layers=2, 
    # optimization_steps=200, 
    # optimizer=qml.AdagradOptimizer(stepsize=0.50)
    # optimizer=qml.GradientDescentOptimizer(stepsize=0.01)
)

In [68]:
optimizer = QmlGradientDescent(100, qml.AdamOptimizer(stepsize=0.05))
hyperparams = {"weights": [4, 1], "layers": 3}
optimizer.set_func_from_problem(knapsack_qaoa, hyperparams)
params = optimizer.minimize([[0.5]*3, [0.5]*3])
probs = knapsack_qaoa.get_probs_func(**hyperparams)(params)
knapsack_qaoa.print_results(probs)

Key: 1001 with probability 0.2868921414050237   | correct: True, value: 2
Key: 1011 with probability 0.12636864081407279   | correct: False
Key: 0000 with probability 0.12034320498414636   | correct: True, value: 0
Key: 0010 with probability 0.10792226893811545   | correct: False
Key: 0001 with probability 0.08008819629313235   | correct: False
Key: 0111 with probability 0.07493252584948648   | correct: False
Key: 0110 with probability 0.0419789271553169   | correct: False
Key: 0101 with probability 0.039230260186012514   | correct: False
Key: 1010 with probability 0.030534652790292723   | correct: False
Key: 1101 with probability 0.026835917746802242   | correct: False
Key: 1111 with probability 0.01657474833900035   | correct: False
Key: 0011 with probability 0.015600905687967563   | correct: False
Key: 1000 with probability 0.01485598977374968   | correct: False
Key: 0100 with probability 0.012043757476370775   | correct: False
Key: 1110 with probability 0.005105959127725542   | cor

In [82]:
optimizer = CEM(epochs=10, samples_per_epoch=10)
hyperparams = {"weights": [4, 1], "layers": 3}
optimizer.set_func_from_problem(knapsack_qaoa, hyperparams)
params = optimizer.minimize(np.array([[0.5]*3, [0.5]*3]))
probs = knapsack_qaoa.get_probs_func(**hyperparams)(params)
knapsack_qaoa.print_results(probs)

[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]]
Epoch 1	Average Elite Score: -0.31252207280875677	Average Score: -0.09085319582821835
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]] with reward: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]]
Epoch 2	Average Elite Score: -0.31252207280875677	Average Score: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]] with reward: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]]
Epoch 3	Average Elite Score: -0.31252207280875677	Average Score: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]] with reward: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.82679429 2.04324415 2.24312847]]
Epoch 4	Average Elite Score: -0.31252207280875677	Average Score: -0.31252207280875677
[[2.11864648 0.77254236 1.25386666]
 [0.826

In [5]:
solver = ProblemSolver(knapsack_qaoa, qml.AdamOptimizer(stepsize=0.50))

In [6]:
solver.run_learning([4, 1])

(tensor([[ 2.07225667],
         [13.99128126]], requires_grad=True),
 tensor([0.05912193, 0.26245265, 0.06660304, 0.02576167, 0.0252872 ,
         0.06769731, 0.00445439, 0.01978466, 0.12371263, 0.01262926,
         0.04060735, 0.09091908, 0.1026911 , 0.07340681, 0.00914174,
         0.01572918], requires_grad=True))

In [7]:
cem = CEM(
    solver=solver,
    epochs=10,
    samples_per_epoch=100,
    elite_frac=0.1,
    process=6
)

cem.minimize(
    init_weights=[1, 1], 
    # mean=[2.0345243512510995, 2.942750372594455]
)

Epoch 1	Average Elite Score: -0.44609163697469095	Average Score: -0.1829265051200329
[2.0457663295777193, 0.3885538357010436] with reward: -0.7477599575486572


KeyboardInterrupt: 

In [13]:
cem.randomize(init_weights=[1, 1])

Epoch 1	Average Elite Score: -0.3825633806073557	Average Score: -0.12373419129605781
[-7.147861346391355, 9.347924610995836] with reward: -0.5678048497728833
Epoch 2	Average Elite Score: -0.362932978179451	Average Score: -0.11454479002779813
[6.689794925041902, -3.8811813854420674] with reward: -0.569855744441671
Epoch 3	Average Elite Score: -0.4507558604393235	Average Score: -0.14094499255572637
[6.689794925041902, -3.8811813854420674] with reward: -0.569855744441671
Epoch 4	Average Elite Score: -0.3481713818898989	Average Score: -0.12556784882292085
[6.689794925041902, -3.8811813854420674] with reward: -0.569855744441671
Epoch 5	Average Elite Score: -0.37607816600768434	Average Score: -0.12379451838521603
[6.689794925041902, -3.8811813854420674] with reward: -0.569855744441671
Epoch 6	Average Elite Score: -0.3731710878383884	Average Score: -0.1147461320326705
[6.689794925041902, -3.8811813854420674] with reward: -0.569855744441671
Epoch 7	Average Elite Score: -0.4510509117545601	Aver

[-4.575296603491294, -0.9036316684903625]

In [16]:
knapsack_qaoa.print_results([5.876428961941668, 1.9278045693719936])

Key: 101 with probability 0.5851258230403462   | correct: True, value: 2
Key: 111 with probability 0.23010160440914704   | correct: False
Key: 001 with probability 0.06187830273109165   | correct: False
Key: 011 with probability 0.05841408055146326   | correct: True, value: 1
Key: 100 with probability 0.03178243587187642   | correct: False
Key: 000 with probability 0.01852700194629529   | correct: True, value: 0
Key: 110 with probability 0.008241419311877003   | correct: False
Key: 010 with probability 0.005929332137900813   | correct: False


In [15]:
import pennylane as qml

def _create_mixing_hamitonian(const=1/2):
    hamiltonian = qml.Identity(0)
    for i in range(3):
        hamiltonian += qml.Hamiltonian([const], [qml.PauliX(i)])
    return hamiltonian
    

cost_operator = knapsack_qaoa._create_cost_operator((1, 1))
def qaoa_layer(gamma, beta):
    qml.qaoa.cost_layer(gamma, cost_operator)
    qml.qaoa.mixer_layer(beta, _create_mixing_hamitonian())

def hadamard_layer(wires):
    for i in range(wires):
        qml.Hadamard(i)

def circuit(params, n_layers=2):
    hadamard_layer(3)
    qml.layer(qaoa_layer, n_layers, params[0], params[1])

dev = qml.device("default.qubit", wires=3)


@qml.qnode(dev)
def cost_function(params):
    circuit(params, n_layers=1)
    x = qml.expval(cost_operator)
    return x

# fig, ax = qml.draw_mpl(cost_function, expansion_strategy="device")([[1], [2]])
# fig.show()
print(qml.draw(cost_function, expansion_strategy="device")([[1], [1]]))

0: ──H──MultiRZ(1.00)─╭MultiRZ(1.00)─╭MultiRZ(-1.00)──H───────────────MultiRZ(1.00)──H────────────
1: ──H────────────────╰MultiRZ(1.00)─│───────────────╭MultiRZ(-1.00)──H──────────────MultiRZ(1.00)
2: ──H──MultiRZ(2.00)────────────────╰MultiRZ(-1.00)─╰MultiRZ(-1.00)──H──────────────MultiRZ(1.00)

─────┤ ╭<𝓗>
───H─┤ ├<𝓗>
───H─┤ ╰<𝓗>


In [21]:
import numpy as np


elite_weights = [[8,2], [4,1], [2,0]]
print(np.var([8, 4, 2]))
_mean = np.mean(elite_weights, axis=0)
print(np.stack((elite_weights), axis = 1))
_cov = np.cov(np.stack((elite_weights), axis = 1), bias=True)
print(_mean)
print(_cov)

6.222222222222221
[[8 4 2]
 [2 1 0]]
[4.66666667 1.        ]
[[6.22222222 2.        ]
 [2.         0.66666667]]
